name: Deploy to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pipx install twine
        pip install .[GUI]
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
      run: |
        pipx run build --sdist
        pipx run build --wheel
        twine upload --skip-existing dist/*
